spring:
   thymeleaf:
   cache: false
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: fuqian
     password: 123456
     url: jdbc:mysql://localhost:3306/onlinechat?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true

mybatis:
  type-aliases-package: cn.edu.ncu.bootwebsocketmybatis.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
     cn.edu.ncu.bootwebsocketmybatis: debug

